// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_timetext = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1554454760);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 1 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timetext = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_timetext, 150);
lv_obj_set_height( ui_timetext, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_timetext, -58 );
lv_obj_set_y( ui_timetext, -16 );
lv_obj_set_align( ui_timetext, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_timetext,"23:59");
lv_textarea_set_placeholder_text(ui_timetext,"Placeholder...");
lv_textarea_set_one_line(ui_timetext,true);
lv_obj_set_style_text_font(ui_timetext, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Image1= NULL;
ui_timetext= NULL;

}
