#!/usr/bin/env python3
"""
Generate LVGL 9 lv_image_dsc_t assets from Figma-exported PNG files.

Default use:
  - full-screen ST7789 frames exported as 1x PNG into firmware/ui/lvgl/screens
  - symbol mapping kept in firmware/ui/lvgl/screens_manifest.json

The same script can also be reused for arbitrary-sized Figma PNG exports by
passing --allow-any-size and pointing manifest/images-dir to another export set.
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path


def repo_firmware_root() -> Path:
    return Path(__file__).resolve().parent.parent


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def blend_over(bg: tuple[int, int, int], fg: tuple[int, int, int, int]) -> tuple[int, int, int]:
    r, g, b, a = fg
    if a >= 255:
        return r, g, b
    br, bg_g, bb = bg
    alpha = a / 255.0
    return (
        int(r * alpha + br * (1.0 - alpha)),
        int(g * alpha + bg_g * (1.0 - alpha)),
        int(b * alpha + bb * (1.0 - alpha)),
    )


def png_to_rgb565_bytes(path: Path, bg_hex: int) -> tuple[int, int, bytes]:
    from PIL import Image

    bg_rgb = ((bg_hex >> 16) & 0xFF, (bg_hex >> 8) & 0xFF, bg_hex & 0xFF)
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    out = bytearray()

    for y in range(height):
        for x in range(width):
            r, g, b, a = image.getpixel((x, y))
            r, g, b = blend_over(bg_rgb, (r, g, b, a))
            out += struct.pack("<H", rgb888_to_rgb565(r, g, b))

    return width, height, bytes(out)


def emit_c_file(out_c: Path, out_h: Path, items: list[tuple[str, str, bytes, int, int]]) -> None:
    guard = out_h.stem.upper() + "_H"
    include_name = out_h.name
    h_lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "lvgl.h"',
        "",
    ]
    c_lines = [
        "/* Auto-generated by scripts/gen_lvgl_screen_assets_from_png.py — do not edit */",
        "",
        f'#include "{include_name}"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
    ]

    for sym, _filename, payload, width, height in items:
      arr = ", ".join(f"0x{byte:02x}" for byte in payload)
      c_lines.append(
          f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {sym}_map[] = {{\n  {arr}\n}};"
      )
      c_lines.append("")
      c_lines.append(f"const lv_image_dsc_t {sym} = {{")
      c_lines.append("  .header = {")
      c_lines.append("    .magic = LV_IMAGE_HEADER_MAGIC,")
      c_lines.append("    .cf = LV_COLOR_FORMAT_RGB565,")
      c_lines.append("    .flags = 0,")
      c_lines.append(f"    .w = {width},")
      c_lines.append(f"    .h = {height},")
      c_lines.append(f"    .stride = {width * 2},")
      c_lines.append("    .reserved_2 = 0,")
      c_lines.append("  },")
      c_lines.append(f"  .data_size = sizeof({sym}_map),")
      c_lines.append(f"  .data = {sym}_map,")
      c_lines.append("  .reserved = NULL,")
      c_lines.append("  .reserved_2 = NULL,")
      c_lines.append("};")
      c_lines.append("")
      h_lines.append(f"extern const lv_image_dsc_t {sym};")
      h_lines.append("")

    h_lines.append(f"#endif /* {guard} */")
    h_lines.append("")

    out_c.write_text("\n".join(c_lines), encoding="utf-8")
    out_h.write_text("\n".join(h_lines), encoding="utf-8")


def load_manifest(path: Path) -> list[tuple[str, str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    items: list[tuple[str, str]] = []
    if not isinstance(data, list):
        raise ValueError(f"manifest must be a JSON array: {path}")
    for entry in data:
        if not isinstance(entry, dict):
            raise ValueError(f"manifest entry must be object: {entry!r}")
        file_name = entry.get("file")
        symbol = entry.get("symbol")
        if not isinstance(file_name, str) or not isinstance(symbol, str):
            raise ValueError(f"manifest entry needs string file/symbol: {entry!r}")
        items.append((file_name, symbol))
    return items


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--images-dir",
        type=Path,
        default=repo_firmware_root() / "ui" / "lvgl" / "screens",
        help="Directory containing exported PNG files",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=repo_firmware_root() / "ui" / "lvgl" / "screens_manifest.json",
        help="JSON mapping of PNG file -> C symbol",
    )
    parser.add_argument(
        "--bg",
        type=lambda value: int(value, 0),
        default=0x071321,
        help="Background RGB888 used when alpha blending transparent pixels",
    )
    parser.add_argument("--width", type=int, default=320, help="Expected exported PNG width")
    parser.add_argument("--height", type=int, default=172, help="Expected exported PNG height")
    parser.add_argument(
        "--allow-any-size",
        action="store_true",
        help="Skip width/height validation (not recommended for ST7789 UI assets)",
    )
    parser.add_argument(
        "--out-c",
        type=Path,
        default=repo_firmware_root() / "generated" / "bb_lvgl_screen_assets.c",
        help="Output .c file path",
    )
    parser.add_argument(
        "--out-h",
        type=Path,
        default=repo_firmware_root() / "generated" / "bb_lvgl_screen_assets.h",
        help="Output .h file path",
    )
    args = parser.parse_args()

    out_c = args.out_c
    out_h = args.out_h

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_h.parent.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest(args.manifest)
    items: list[tuple[str, str, bytes, int, int]] = []

    for file_name, symbol in manifest:
        png = args.images_dir / file_name
        if not png.is_file():
            print(f"missing {png}", file=sys.stderr)
            return 1
        width, height, raw = png_to_rgb565_bytes(png, args.bg)
        if not args.allow_any_size and (width != args.width or height != args.height):
            print(
                f"invalid size for {png}: got {width}x{height}, expected {args.width}x{args.height}",
                file=sys.stderr,
            )
            return 1
        print(f"convert {file_name} -> {symbol} ({width}x{height})", file=sys.stderr)
        items.append((symbol, file_name, raw, width, height))

    emit_c_file(out_c, out_h, items)
    print(f"Wrote {out_c} and {out_h}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
