#!/usr/bin/env python3
"""
从 firmware/assets/svg 批量生成 LVGL 9 lv_image_dsc_t（RGB565），供 bb_lvgl_display 使用。

依赖：Node.js（npx sharp-cli）、Python 3 + Pillow。

  cd firmware && make gen-lvgl-assets
"""

from __future__ import annotations

import argparse
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path


def repo_firmware_root() -> Path:
    return Path(__file__).resolve().parent.parent


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def blend_over(bg: tuple[int, int, int], fg: tuple[int, int, int, int]) -> tuple[int, int, int]:
    r, g, b, a = fg
    if a >= 255:
        return r, g, b
    br, bg_, bb = bg
    a_f = a / 255.0
    return (
        int(r * a_f + br * (1.0 - a_f)),
        int(g * a_f + bg_ * (1.0 - a_f)),
        int(b * a_f + bb * (1.0 - a_f)),
    )


def png_to_rgb565_bytes(path: Path, bg_hex: int) -> tuple[int, int, bytes]:
    from PIL import Image

    br = (bg_hex >> 16) & 0xFF
    bg_g = (bg_hex >> 8) & 0xFF
    bb = bg_hex & 0xFF
    bg_rgb = (br, bg_g, bb)

    im = Image.open(path).convert("RGBA")
    w, h = im.size
    out = bytearray()
    for y in range(h):
        for x in range(w):
            px = im.getpixel((x, y))
            r, g, b, a = px
            r, g, b = blend_over(bg_rgb, (r, g, b, a))
            u16 = rgb888_to_rgb565(r, g, b)
            out += struct.pack("<H", u16)
    stride = w * 2
    return w, h, bytes(out)


def emit_c_file(
    out_c: Path,
    out_h: Path,
    items: list[tuple[str, str, bytes, int, int]],
) -> None:
    """items: (c_symbol, description, raw_rgb565, w, h) — raw excludes header, image payload only."""

    guard = "BB_LVGL_ASSETS_H"
    h_lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "lvgl.h"',
        "",
    ]
    c_lines = [
        '/* Auto-generated by scripts/gen_lvgl_assets_from_svg.py — do not edit */',
        "",
        '#include "bb_lvgl_assets.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
    ]

    for sym, _desc, payload, w, h in items:
        arr = ", ".join(f"0x{b:02x}" for b in payload)
        c_lines.append(
            f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {sym}_map[] = {{\n  {arr}\n}};"
        )
        c_lines.append("")
        c_lines.append(f"const lv_image_dsc_t {sym} = {{")
        c_lines.append("  .header = {")
        c_lines.append("    .magic = LV_IMAGE_HEADER_MAGIC,")
        c_lines.append("    .cf = LV_COLOR_FORMAT_RGB565,")
        c_lines.append(f"    .flags = 0,")
        c_lines.append(f"    .w = {w},")
        c_lines.append(f"    .h = {h},")
        c_lines.append(f"    .stride = {w * 2},")
        c_lines.append("    .reserved_2 = 0,")
        c_lines.append("  },")
        c_lines.append(f"  .data_size = sizeof({sym}_map),")
        c_lines.append(f"  .data = {sym}_map,")
        c_lines.append("  .reserved = NULL,")
        c_lines.append("  .reserved_2 = NULL,")
        c_lines.append("};")
        c_lines.append("")
        h_lines.append(f"extern const lv_image_dsc_t {sym};")
        h_lines.append("")

    h_lines.append("")
    h_lines.append(f"#endif /* {guard} */")
    h_lines.append("")

    out_c.write_text("\n".join(c_lines), encoding="utf-8")
    out_h.write_text("\n".join(h_lines), encoding="utf-8")


def sharp_rasterize(svg: Path, png_out: Path, size: int) -> None:
    sharp = shutil.which("npx")
    if not sharp:
        raise RuntimeError("npx not found")
    cmd = [
        "npx",
        "--yes",
        "sharp-cli",
        "-i",
        str(svg),
        "-o",
        str(png_out),
        "resize",
        str(size),
        str(size),
    ]
    subprocess.run(cmd, check=True, cwd=str(svg.parent))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=20, help="Icon square size (px)")
    ap.add_argument(
        "--bg",
        type=lambda x: int(x, 0),
        default=0x0A0E0C,
        help="Background RGB888 for alpha blend (match UI_SCR_BG)",
    )
    args = ap.parse_args()

    root = repo_firmware_root()
    svg_dir = root / "assets" / "svg"
    out_c = root / "src" / "bb_lvgl_assets.c"
    out_h = root / "include" / "bb_lvgl_assets.h"

    mapping = [
        ("icon_ready.svg", "bb_img_ready"),
        ("icon_tx.svg", "bb_img_tx"),
        ("icon_rx.svg", "bb_img_rx"),
        ("icon_err.svg", "bb_img_err"),
        ("icon_task.svg", "bb_img_task"),
        ("icon_speak.svg", "bb_img_speak"),
        ("icon_rec_1.svg", "bb_img_rec_1"),
        ("icon_rec_2.svg", "bb_img_rec_2"),
        ("icon_rec_3.svg", "bb_img_rec_3"),
        ("icon_home.svg", "bb_img_mode_home"),
        ("icon_cloud.svg", "bb_img_mode_cloud"),
        ("logo_claw.svg", "bb_img_logo_claw"),
        ("logo_openclaw.svg", "bb_img_logo_openclaw"),
        ("logo_openclaw_panel.svg", "bb_img_logo_openclaw_panel"),
    ]

    items: list[tuple[str, str, bytes, int, int]] = []

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        for svg_name, sym in mapping:
            svg = svg_dir / svg_name
            if not svg.is_file():
                print(f"skip missing {svg}", file=sys.stderr)
                continue
            png = tmp / (sym + ".png")
            print(f"rasterize {svg_name} -> {sym} ...", file=sys.stderr)
            sharp_rasterize(svg, png, args.size)
            w, h, raw = png_to_rgb565_bytes(png, args.bg)
            items.append((sym, svg_name, raw, w, h))

    if not items:
        print("No SVG processed.", file=sys.stderr)
        return 1

    emit_c_file(out_c, out_h, items)
    print(f"Wrote {out_c} and {out_h}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
