#pragma once

#include "sdkconfig.h"

/* ── Board selection: include board-specific pin map and hardware config ── */
#if defined(CONFIG_BBCLAW_BOARD_ATK_DNESP32S3_BOX)
#include "../boards/atk-dnesp32s3-box/board_config.h"
#elif defined(CONFIG_BBCLAW_BOARD_BREADBOARD) || !defined(BBCLAW_DISPLAY_BUS_SPI)
#include "../boards/breadboard/board_config.h"
#endif

/* ── Default bus flags (boards that predate the bus flag) ── */
#ifndef BBCLAW_DISPLAY_BUS_SPI
#define BBCLAW_DISPLAY_BUS_SPI 1
#endif
#ifndef BBCLAW_DISPLAY_BUS_I80
#define BBCLAW_DISPLAY_BUS_I80 0
#endif

#ifndef BBCLAW_XL9555_ENABLE
#define BBCLAW_XL9555_ENABLE 0
#endif

#ifndef BBCLAW_NODE_ID
#define BBCLAW_NODE_ID "bbclaw-esp32s3"
#endif

#ifndef BBCLAW_GATEWAY_URL
#define BBCLAW_GATEWAY_URL "ws://192.168.1.10:19089/gateway"
#endif

#ifndef BBCLAW_PAIRING_TOKEN
#define BBCLAW_PAIRING_TOKEN ""
#endif

#ifndef BBCLAW_WIFI_SSID
#ifdef CONFIG_BBCLAW_WIFI_SSID
#define BBCLAW_WIFI_SSID CONFIG_BBCLAW_WIFI_SSID
#else
#define BBCLAW_WIFI_SSID ""
#endif
#endif

#ifndef BBCLAW_WIFI_PASSWORD
#ifdef CONFIG_BBCLAW_WIFI_PASSWORD
#define BBCLAW_WIFI_PASSWORD CONFIG_BBCLAW_WIFI_PASSWORD
#else
#define BBCLAW_WIFI_PASSWORD ""
#endif
#endif

#ifndef BBCLAW_WIFI_STA_MAX_RETRY
#define BBCLAW_WIFI_STA_MAX_RETRY 3
#endif

#ifndef BBCLAW_WIFI_STA_CONNECT_TIMEOUT_MS
#define BBCLAW_WIFI_STA_CONNECT_TIMEOUT_MS 30000
#endif

#ifndef BBCLAW_WIFI_NVS_NAMESPACE
#define BBCLAW_WIFI_NVS_NAMESPACE "bbwifi"
#endif

#ifndef BBCLAW_WIFI_NVS_KEY_SSID
#define BBCLAW_WIFI_NVS_KEY_SSID "sta_ssid"
#endif

#ifndef BBCLAW_WIFI_NVS_KEY_PASSWORD
#define BBCLAW_WIFI_NVS_KEY_PASSWORD "sta_pass"
#endif

#ifndef BBCLAW_WIFI_MAX_SAVED
#define BBCLAW_WIFI_MAX_SAVED 4
#endif

#ifndef BBCLAW_WIFI_AP_SSID_PREFIX
#define BBCLAW_WIFI_AP_SSID_PREFIX "BBClaw-Setup"
#endif

#ifndef BBCLAW_WIFI_AP_PASSWORD
#define BBCLAW_WIFI_AP_PASSWORD "bbclaw1234"
#endif

#ifndef BBCLAW_WIFI_AP_CHANNEL
#define BBCLAW_WIFI_AP_CHANNEL 6
#endif

#ifndef BBCLAW_WIFI_AP_MAX_CONNECTIONS
#define BBCLAW_WIFI_AP_MAX_CONNECTIONS 4
#endif

#ifndef BBCLAW_ADAPTER_BASE_URL
#ifdef CONFIG_BBCLAW_ADAPTER_BASE_URL
#define BBCLAW_ADAPTER_BASE_URL CONFIG_BBCLAW_ADAPTER_BASE_URL
#else
#define BBCLAW_ADAPTER_BASE_URL "http://192.168.10.26:18080"
#endif
#endif

#ifndef BBCLAW_TRANSPORT_PROFILE
#if defined(CONFIG_BBCLAW_TRANSPORT_PROFILE_CLOUD_SAAS)
#define BBCLAW_TRANSPORT_PROFILE "cloud_saas"
#else
#define BBCLAW_TRANSPORT_PROFILE "local_home"
#endif
#endif

#ifndef BBCLAW_CLOUD_BASE_URL
#ifdef CONFIG_BBCLAW_CLOUD_BASE_URL
#define BBCLAW_CLOUD_BASE_URL CONFIG_BBCLAW_CLOUD_BASE_URL
#else
#define BBCLAW_CLOUD_BASE_URL "http://bbclaw.daboluo.cc:38082"
#endif
#endif

#ifndef BBCLAW_CLOUD_AUDIO_STREAMING_READY
#define BBCLAW_CLOUD_AUDIO_STREAMING_READY 1
#endif

/** 为 1 时：每包 /v1/stream/chunk 打印 wall_span_ms / gap_prev_ms / http_ms，便于对照服务端 AUDIO_TOO_LONG */
#ifndef BBCLAW_ADAPTER_STREAM_CHUNK_DIAG
#define BBCLAW_ADAPTER_STREAM_CHUNK_DIAG 1
#endif

#ifndef BBCLAW_ENABLE_DISPLAY_PULL
#ifdef CONFIG_BBCLAW_ENABLE_DISPLAY_PULL
#define BBCLAW_ENABLE_DISPLAY_PULL 1
#else
#define BBCLAW_ENABLE_DISPLAY_PULL 0
#endif
#endif

/** 云上 deviceId：BBClaw-<固件版本>-<MAC 后三字节>（与 SoftAP「前缀-后缀」同源）；运行时见 bb_identity.c */
#ifndef BBCLAW_DEVICE_ID
const char *bbclaw_device_id(void);
#define BBCLAW_DEVICE_ID (bbclaw_device_id())
#endif

#ifndef BBCLAW_SESSION_KEY
const char *bbclaw_session_key(void);
#define BBCLAW_SESSION_KEY (bbclaw_session_key())
#endif

#ifndef BBCLAW_STREAM_CODEC
#define BBCLAW_STREAM_CODEC "opus"
#endif

#ifndef BBCLAW_LOCAL_LOOPBACK_ONLY
#define BBCLAW_LOCAL_LOOPBACK_ONLY 0
#endif

#ifndef BBCLAW_LOCAL_LOOPBACK_MAX_MS
#define BBCLAW_LOCAL_LOOPBACK_MAX_MS 8000
#endif

#ifndef BBCLAW_ENABLE_TTS_PLAYBACK
#ifdef CONFIG_BBCLAW_ENABLE_TTS_PLAYBACK
#define BBCLAW_ENABLE_TTS_PLAYBACK 1
#else
#define BBCLAW_ENABLE_TTS_PLAYBACK 0
#endif
#endif

#ifndef BBCLAW_TTS_SAMPLE_RATE
#define BBCLAW_TTS_SAMPLE_RATE 16000
#endif

#ifndef BBCLAW_TTS_CHANNELS
#define BBCLAW_TTS_CHANNELS 1
#endif

/** TTS 播放音量百分比（0-100），100=原始音量，50=减半 */
#ifndef BBCLAW_TTS_VOLUME_PCT
#define BBCLAW_TTS_VOLUME_PCT 80
#endif

#ifndef BBCLAW_SPK_TEST_ON_BOOT
#define BBCLAW_SPK_TEST_ON_BOOT 1
#endif

#ifndef BBCLAW_PA_EN_GPIO
#define BBCLAW_PA_EN_GPIO -1
#endif

#ifndef BBCLAW_PA_EN_ACTIVE_LEVEL
#define BBCLAW_PA_EN_ACTIVE_LEVEL 1
#endif

#ifndef BBCLAW_PA_EN_PROBE_ON_BOOT
#define BBCLAW_PA_EN_PROBE_ON_BOOT 0
#endif

#ifndef BBCLAW_PA_EN_PROBE_GPIO1
#define BBCLAW_PA_EN_PROBE_GPIO1 13
#endif

#ifndef BBCLAW_PA_EN_PROBE_GPIO2
#define BBCLAW_PA_EN_PROBE_GPIO2 -1
#endif

#ifndef BBCLAW_PA_EN_PROBE_GPIO3
#define BBCLAW_PA_EN_PROBE_GPIO3 -1
#endif

/**
 * PTT 只使用一个引脚（BBCLAW_PTT_GPIO）。BOOT0 与外接键二选一；若要两键同时各管不同逻辑需改代码（当前无第二路 PTT）。
 * 外接键实测：空闲 0、按下 1 → ACTIVE_LEVEL=1、PULL_UP=0。
 */
#ifndef BBCLAW_PTT_GPIO
#define BBCLAW_PTT_GPIO 7
#endif

#ifndef BBCLAW_PTT_ACTIVE_LEVEL
#define BBCLAW_PTT_ACTIVE_LEVEL 1
#endif

#ifndef BBCLAW_PTT_PULL_UP
#define BBCLAW_PTT_PULL_UP 0
#endif

#ifndef BBCLAW_PTT_DEBOUNCE_MS
#define BBCLAW_PTT_DEBOUNCE_MS 30
#endif

/** 外接按键测试（仅调试用）：设为 -1 关闭；与 PTT 同脚时不要开，避免重复配置 GPIO */
#ifndef BBCLAW_BUTTON_TEST_GPIO
#define BBCLAW_BUTTON_TEST_GPIO -1
#endif
#ifndef BBCLAW_BUTTON_TEST_PULL_UP
#define BBCLAW_BUTTON_TEST_PULL_UP 0
#endif
#ifndef BBCLAW_BUTTON_TEST_INTERVAL_MS
#define BBCLAW_BUTTON_TEST_INTERVAL_MS 50
#endif

#ifndef BBCLAW_MOTOR_ENABLE
#define BBCLAW_MOTOR_ENABLE 1
#endif

#ifndef BBCLAW_MOTOR_GPIO
#define BBCLAW_MOTOR_GPIO 21
#endif

#ifndef BBCLAW_MOTOR_ACTIVE_LEVEL
#define BBCLAW_MOTOR_ACTIVE_LEVEL 1
#endif

/** PTT 按下：偏心马达需 ~50ms+ 才易感知，过短会像“没震” */
#ifndef BBCLAW_MOTOR_PULSE_SHORT_MS
#define BBCLAW_MOTOR_PULSE_SHORT_MS 500
#endif

/** PTT 松开：比按下略短、略轻，形成“按下—松开”一对触觉 */
#ifndef BBCLAW_MOTOR_PULSE_RELEASE_MS
#define BBCLAW_MOTOR_PULSE_RELEASE_MS 400
#endif

#ifndef BBCLAW_MOTOR_PULSE_LONG_MS
#define BBCLAW_MOTOR_PULSE_LONG_MS 400
#endif

#ifndef BBCLAW_MOTOR_PULSE_GAP_MS
#define BBCLAW_MOTOR_PULSE_GAP_MS 100
#endif

#ifndef BBCLAW_STATUS_LED_ENABLE
#define BBCLAW_STATUS_LED_ENABLE 1
#endif

#ifndef BBCLAW_STATUS_LED_KIND_RGB_MODULE
#define BBCLAW_STATUS_LED_KIND_RGB_MODULE 0
#endif

#ifndef BBCLAW_STATUS_LED_R_GPIO
#define BBCLAW_STATUS_LED_R_GPIO 2
#endif

#ifndef BBCLAW_STATUS_LED_Y_GPIO
#define BBCLAW_STATUS_LED_Y_GPIO 4
#endif

#ifndef BBCLAW_STATUS_LED_G_GPIO
#define BBCLAW_STATUS_LED_G_GPIO 5
#endif

#ifndef BBCLAW_STATUS_LED_RGB_G_GPIO
#define BBCLAW_STATUS_LED_RGB_G_GPIO 4
#endif

#ifndef BBCLAW_STATUS_LED_RGB_B_GPIO
#define BBCLAW_STATUS_LED_RGB_B_GPIO 5
#endif

#ifndef BBCLAW_STATUS_LED_GPIO_ON_LEVEL
#define BBCLAW_STATUS_LED_GPIO_ON_LEVEL 1
#endif

/** 开机 RYG 跑马灯：依次点亮 R→Y→G，每色停留步长；整段时长 = 3 × 步长 × 圈数 */
#ifndef BBCLAW_STATUS_LED_BOOT_ANIM_ENABLE
#define BBCLAW_STATUS_LED_BOOT_ANIM_ENABLE 1
#endif
#ifndef BBCLAW_STATUS_LED_BOOT_ANIM_STEP_MS
#define BBCLAW_STATUS_LED_BOOT_ANIM_STEP_MS 200
#endif
#ifndef BBCLAW_STATUS_LED_BOOT_ANIM_LOOPS
#define BBCLAW_STATUS_LED_BOOT_ANIM_LOOPS 2
#endif

#ifndef BBCLAW_AUDIO_SAMPLE_RATE
#define BBCLAW_AUDIO_SAMPLE_RATE 16000
#endif

#ifndef BBCLAW_AUDIO_I2S_DMA_DESC_NUM
#define BBCLAW_AUDIO_I2S_DMA_DESC_NUM 4
#endif

#ifndef BBCLAW_AUDIO_I2S_DMA_FRAME_NUM
#define BBCLAW_AUDIO_I2S_DMA_FRAME_NUM 120
#endif

#ifndef BBCLAW_AUDIO_INPUT_SOURCE
#define BBCLAW_AUDIO_INPUT_SOURCE "inmp441"
#endif

#ifndef BBCLAW_AUDIO_CHANNELS
#define BBCLAW_AUDIO_CHANNELS 1
#endif

#ifndef BBCLAW_AUDIO_RX_STEREO_CAPTURE
#define BBCLAW_AUDIO_RX_STEREO_CAPTURE 1
#endif

#ifndef BBCLAW_AUDIO_FRAME_MS
#define BBCLAW_AUDIO_FRAME_MS 20
#endif

#ifndef BBCLAW_STREAM_CHUNK_MS
#define BBCLAW_STREAM_CHUNK_MS 60
#endif

#ifndef BBCLAW_AUDIO_I2S_SLOT_BITS
#define BBCLAW_AUDIO_I2S_SLOT_BITS 16
#endif

#ifndef BBCLAW_AUDIO_RX_SHIFT_BITS
#define BBCLAW_AUDIO_RX_SHIFT_BITS 16
#endif

#ifndef BBCLAW_AUDIO_RX_MONO_PICK_RIGHT
#define BBCLAW_AUDIO_RX_MONO_PICK_RIGHT 0
#endif

#ifndef BBCLAW_AUDIO_RX_AUTO_CHANNEL_LOCK
#define BBCLAW_AUDIO_RX_AUTO_CHANNEL_LOCK 1
#endif

#ifndef BBCLAW_AUDIO_RX_WARMUP_SAMPLES
#define BBCLAW_AUDIO_RX_WARMUP_SAMPLES 256
#endif

#ifndef BBCLAW_AUDIO_INMP441_GAIN_NUM
#define BBCLAW_AUDIO_INMP441_GAIN_NUM 8
#endif

#ifndef BBCLAW_AUDIO_INMP441_GAIN_DEN
#define BBCLAW_AUDIO_INMP441_GAIN_DEN 1
#endif

#ifndef BBCLAW_AUDIO_INMP441_HPF_ENABLE
#define BBCLAW_AUDIO_INMP441_HPF_ENABLE 1
#endif

#ifndef BBCLAW_AUDIO_INMP441_HPF_ALPHA_Q15
#define BBCLAW_AUDIO_INMP441_HPF_ALPHA_Q15 32113
#endif

#ifndef BBCLAW_AUDIO_DIAG_LOG_INTERVAL_MS
#define BBCLAW_AUDIO_DIAG_LOG_INTERVAL_MS 1000
#endif

#ifndef BBCLAW_AUDIO_TX_EXPERIMENT
/* 1=A stereo32 [v,v], 2=B stereo16 [v,v], 3=C mono16 left-slot */
#define BBCLAW_AUDIO_TX_EXPERIMENT 1
#endif

#ifndef BBCLAW_AUDIO_IO_TIMEOUT_MS
#define BBCLAW_AUDIO_IO_TIMEOUT_MS 200
#endif

#ifndef BBCLAW_AUDIO_TX_RATE_COMP_NUM
#define BBCLAW_AUDIO_TX_RATE_COMP_NUM 1
#endif

#ifndef BBCLAW_AUDIO_TX_RATE_COMP_DEN
#define BBCLAW_AUDIO_TX_RATE_COMP_DEN 1
#endif

#ifndef BBCLAW_VAD_ENABLE
#define BBCLAW_VAD_ENABLE 1
#endif

#ifndef BBCLAW_VAD_MIN_DURATION_MS
#define BBCLAW_VAD_MIN_DURATION_MS 500
#endif

#ifndef BBCLAW_VAD_MIN_NONZERO_PERMILLE
#define BBCLAW_VAD_MIN_NONZERO_PERMILLE 40
#endif

#ifndef BBCLAW_VAD_MIN_MEAN_ABS
#define BBCLAW_VAD_MIN_MEAN_ABS 120
#endif

/** PTT 按下后先本地开麦；仅当累计特征满足下列门限才调用 adapter stream/start（避免无声占满并发流） */
#ifndef BBCLAW_VAD_ARM_MIN_DURATION_MS
#define BBCLAW_VAD_ARM_MIN_DURATION_MS 240
#endif

#ifndef BBCLAW_VAD_ARM_MIN_NONZERO_PERMILLE
#define BBCLAW_VAD_ARM_MIN_NONZERO_PERMILLE 40
#endif

#ifndef BBCLAW_VAD_ARM_MIN_MEAN_ABS
#define BBCLAW_VAD_ARM_MIN_MEAN_ABS 80
#endif

/** 预检阶段最长等待（毫秒），超时则放弃本轮（需松键再按）；0 表示不限制 */
#ifndef BBCLAW_VAD_ARM_MAX_WAIT_MS
#define BBCLAW_VAD_ARM_MAX_WAIT_MS 15000
#endif

#ifndef BBCLAW_HTTP_TIMEOUT_MS
#define BBCLAW_HTTP_TIMEOUT_MS 20000
#endif

#ifndef BBCLAW_HTTP_STREAM_FINISH_TIMEOUT_MS
#define BBCLAW_HTTP_STREAM_FINISH_TIMEOUT_MS 90000
#endif

#ifndef BBCLAW_ADAPTER_HEARTBEAT_INTERVAL_MS
#define BBCLAW_ADAPTER_HEARTBEAT_INTERVAL_MS 5000
#endif

#ifndef BBCLAW_ADAPTER_HEARTBEAT_FAIL_THRESHOLD
#define BBCLAW_ADAPTER_HEARTBEAT_FAIL_THRESHOLD 2
#endif

#ifndef BBCLAW_HTTP_RETRY_COUNT
#define BBCLAW_HTTP_RETRY_COUNT 2
#endif

#ifndef BBCLAW_HTTP_RETRY_DELAY_MS
#define BBCLAW_HTTP_RETRY_DELAY_MS 200
#endif

#ifndef BBCLAW_ADAPTER_BOOT_HEALTH_RETRIES
#define BBCLAW_ADAPTER_BOOT_HEALTH_RETRIES 8
#endif

#ifndef BBCLAW_ADAPTER_BOOT_HEALTH_DELAY_MS
#define BBCLAW_ADAPTER_BOOT_HEALTH_DELAY_MS 500
#endif

#ifndef BBCLAW_ES8311_I2C_PORT
#define BBCLAW_ES8311_I2C_PORT 0
#endif

#ifndef BBCLAW_ES8311_I2C_SDA_GPIO
#define BBCLAW_ES8311_I2C_SDA_GPIO 8
#endif

#ifndef BBCLAW_ES8311_I2C_SCL_GPIO
#define BBCLAW_ES8311_I2C_SCL_GPIO 6
#endif

#ifndef BBCLAW_ES8311_I2C_ADDR
#define BBCLAW_ES8311_I2C_ADDR 0x18
#endif

#ifndef BBCLAW_ES8311_I2S_MCK_GPIO
#define BBCLAW_ES8311_I2S_MCK_GPIO 2
#endif

#ifndef BBCLAW_ES8311_I2S_BCK_GPIO
#define BBCLAW_ES8311_I2S_BCK_GPIO 16
#endif

#ifndef BBCLAW_ES8311_I2S_WS_GPIO
#define BBCLAW_ES8311_I2S_WS_GPIO 15
#endif

#ifndef BBCLAW_ES8311_I2S_DO_GPIO
#define BBCLAW_ES8311_I2S_DO_GPIO 17
#endif

#ifndef BBCLAW_ES8311_I2S_DI_GPIO
#define BBCLAW_ES8311_I2S_DI_GPIO 18
#endif

#ifndef BBCLAW_ST7789_HOST
#define BBCLAW_ST7789_HOST 2
#endif

#ifndef BBCLAW_ST7789_SCLK_GPIO
#define BBCLAW_ST7789_SCLK_GPIO 12
#endif

#ifndef BBCLAW_ST7789_MOSI_GPIO
#define BBCLAW_ST7789_MOSI_GPIO 11
#endif

#ifndef BBCLAW_ST7789_CS_GPIO
#define BBCLAW_ST7789_CS_GPIO 10
#endif

#ifndef BBCLAW_ST7789_DC_GPIO
#define BBCLAW_ST7789_DC_GPIO 9
#endif

#ifndef BBCLAW_ST7789_RST_GPIO
#define BBCLAW_ST7789_RST_GPIO 14
#endif

#ifndef BBCLAW_ST7789_BL_GPIO
#define BBCLAW_ST7789_BL_GPIO 13
#endif

#ifndef BBCLAW_ST7789_WIDTH
#define BBCLAW_ST7789_WIDTH 320
#endif

#ifndef BBCLAW_ST7789_HEIGHT
#define BBCLAW_ST7789_HEIGHT 172
#endif

/** ST7789 / LVGL「ME / AI」各一栏的 UTF-8 缓冲（助手常带多行 Markdown，200 易截断） */
#ifndef BBCLAW_DISPLAY_CHAT_LINE_LEN
#define BBCLAW_DISPLAY_CHAT_LINE_LEN 512
#endif

/** 保留最近若干轮对话，供左右切换回看（仅固件 RAM，与 LVGL 历史无关） */
#ifndef BBCLAW_DISPLAY_CHAT_HISTORY
#define BBCLAW_DISPLAY_CHAT_HISTORY 8
#endif

/** READY 状态下无操作多久后自动回到待机画面（清掉聊天历史），单位 ms；0 = 不自动回待机 */
#ifndef BBCLAW_DISPLAY_STANDBY_TIMEOUT_MS
#define BBCLAW_DISPLAY_STANDBY_TIMEOUT_MS 120000
#endif

/**
 * 屏幕旋转角（度）：0 / 90 / 180 / 270。由板级 board_config.h 映射到 ST7789 swap/mirror。
 * 未在板级定义时默认为 0（与仅写死 SWAP/MIRROR 的旧板卡行为一致）。
 */
#ifndef BBCLAW_DISPLAY_ROTATION_DEG
#define BBCLAW_DISPLAY_ROTATION_DEG 0
#endif

/**
 * Display orientation defaults — boards define these in board_config.h.
 * These are fallbacks only.
 */
#ifndef BBCLAW_ST7789_X_GAP
#define BBCLAW_ST7789_X_GAP 0
#endif

#ifndef BBCLAW_ST7789_Y_GAP
#define BBCLAW_ST7789_Y_GAP 34
#endif

#ifndef BBCLAW_ST7789_PCLK_HZ
#define BBCLAW_ST7789_PCLK_HZ (20 * 1000 * 1000)
#endif

#ifndef BBCLAW_ST7789_SWAP_XY
#define BBCLAW_ST7789_SWAP_XY 1
#endif

#ifndef BBCLAW_ST7789_MIRROR_X
#define BBCLAW_ST7789_MIRROR_X 0
#endif

#ifndef BBCLAW_ST7789_MIRROR_Y
#define BBCLAW_ST7789_MIRROR_Y 0
#endif

#ifndef BBCLAW_ST7789_INVERT_COLOR
#define BBCLAW_ST7789_INVERT_COLOR 0
#endif

#ifndef BBCLAW_ST7789_RGB_ORDER_BGR
#define BBCLAW_ST7789_RGB_ORDER_BGR 0
#endif

#ifndef BBCLAW_ST7789_SWAP_BYTES
#define BBCLAW_ST7789_SWAP_BYTES 1
#endif
