package envfile

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/daboluocc/bbclaw/adapter/internal/detect"
)

// Values represents .env key-value pairs
type Values map[string]string

var shellSafePattern = regexp.MustCompile(`^[A-Za-z0-9_./:@,=+-]*$`)

// Parse reads and parses a .env file
func Parse(path string) (Values, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Values{}, nil
		}
		return nil, err
	}

	result := make(Values)
	lines := strings.Split(string(data), "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Strip quotes
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
			}
		}

		result[key] = value
	}

	return result, nil
}

// shellQuote quotes a value for safe use in .env files
func shellQuote(v string) string {
	if shellSafePattern.MatchString(v) {
		return v
	}
	// Escape single quotes by replacing ' with '\''
	escaped := strings.ReplaceAll(v, "'", "'\\''")
	return "'" + escaped + "'"
}

// Render generates a formatted .env file content
func Render(values Values, env *detect.Environment) string {
	var lines []string

	lines = append(lines, "# adapter/.env — generated by bbclaw-adapter doctor")
	lines = append(lines, fmt.Sprintf("# Last sync: %s", time.Now().Format(time.RFC3339)))
	lines = append(lines, "# Re-run `bbclaw-adapter doctor --fix` after installing/uninstalling a driver locally.")
	lines = append(lines, "")

	emit := func(comment string, keys []string) {
		// Only emit section if at least one key has a non-empty value
		anyPresent := false
		for _, k := range keys {
			if values[k] != "" {
				anyPresent = true
				break
			}
		}
		if !anyPresent {
			return
		}

		lines = append(lines, comment)
		for _, k := range keys {
			if v := values[k]; v != "" {
				lines = append(lines, fmt.Sprintf("%s=%s", k, shellQuote(v)))
			}
		}
		lines = append(lines, "")
	}

	emit("# OpenClaw gateway (auto-extracted from ~/.openclaw/openclaw.json)",
		[]string{"OPENCLAW_AUTH_TOKEN", "OPENCLAW_WS_URL"})
	emit("# Default agent driver (heuristic: first detected)",
		[]string{"AGENT_DEFAULT_DRIVER"})
	emit("# Ollama (auto-detected installed model)",
		[]string{"OLLAMA_MODEL"})
	emit("# Voice path — ASR + TTS providers. Replace placeholders with real\n# keys to enable PTT (see .env.example for full provider docs).",
		[]string{"ASR_PROVIDER", "ASR_LOCAL_BIN", "ASR_LOCAL_TEXT_PATH", "ASR_READINESS_PROBE",
			"ASR_APP_ID", "ASR_API_KEY", "ASR_BASE_URL", "ASR_MODEL",
			"TTS_PROVIDER", "TTS_APP_ID", "TTS_TOKEN",
			"TTS_LOCAL_BIN", "TTS_LOCAL_ARGS", "TTS_LOCAL_OUTPUT_FORMAT"})
	emit("# Cloud relay (set both to enable cloud_saas firmware support)",
		[]string{"CLOUD_WS_URL", "CLOUD_AUTH_TOKEN"})
	emit("# Production hardening",
		[]string{"ADAPTER_AUTH_TOKEN"})

	// Tail: anything we didn't explicitly group
	grouped := map[string]bool{
		"OPENCLAW_AUTH_TOKEN": true, "OPENCLAW_WS_URL": true, "AGENT_DEFAULT_DRIVER": true,
		"OLLAMA_MODEL": true,
		"ASR_PROVIDER": true, "ASR_LOCAL_BIN": true, "ASR_LOCAL_TEXT_PATH": true, "ASR_READINESS_PROBE": true,
		"ASR_APP_ID": true, "ASR_API_KEY": true, "ASR_BASE_URL": true, "ASR_MODEL": true,
		"TTS_PROVIDER": true, "TTS_APP_ID": true, "TTS_TOKEN": true,
		"TTS_LOCAL_BIN": true, "TTS_LOCAL_ARGS": true, "TTS_LOCAL_OUTPUT_FORMAT": true,
		"CLOUD_WS_URL": true, "CLOUD_AUTH_TOKEN": true, "ADAPTER_AUTH_TOKEN": true,
	}

	var extras []string
	for k, v := range values {
		if !grouped[k] && v != "" {
			extras = append(extras, fmt.Sprintf("%s=%s", k, shellQuote(v)))
		}
	}

	if len(extras) > 0 {
		lines = append(lines, "# Other (preserved from your previous .env)")
		lines = append(lines, extras...)
		lines = append(lines, "")
	}

	return strings.Join(lines, "\n")
}

// BuildValues constructs the .env values from detection results
func BuildValues(existing Values, env *detect.Environment, reset bool) Values {
	var values Values
	if reset {
		values = make(Values)
	} else {
		values = make(Values)
		for k, v := range existing {
			values[k] = v
		}
	}

	setIfUnset := func(key, val string) {
		if val != "" && values[key] == "" {
			values[key] = val
		}
	}

	// OpenClaw
	if env.OpenClaw.Present {
		if token, ok := env.OpenClaw.Data["token"].(string); ok && token != "" {
			setIfUnset("OPENCLAW_AUTH_TOKEN", token)
		}
		if port, ok := env.OpenClaw.Data["port"].(int); ok && port != 18789 {
			setIfUnset("OPENCLAW_WS_URL", fmt.Sprintf("ws://127.0.0.1:%d", port))
		}
	}

	// Default driver
	if defaultDriver := env.PickDefaultDriver(); defaultDriver != "" {
		setIfUnset("AGENT_DEFAULT_DRIVER", defaultDriver)
	}

	// Ollama model
	if env.Ollama.Present {
		if models, ok := env.Ollama.Data["models"].([]string); ok && len(models) > 0 {
			setIfUnset("OLLAMA_MODEL", models[0])
		}
	}

	// Doubao import
	if env.Doubao.Present {
		if mapped, ok := env.Doubao.Data["mapped"].(map[string]string); ok {
			for k, v := range mapped {
				setIfUnset(k, v)
			}
			// If we have Doubao credentials, set provider
			if values["ASR_APP_ID"] != "" && values["ASR_API_KEY"] != "" {
				values["ASR_PROVIDER"] = "doubao_native"
				delete(values, "ASR_LOCAL_BIN")
				delete(values, "ASR_LOCAL_TEXT_PATH")
				delete(values, "ASR_READINESS_PROBE")
			}
			if values["TTS_APP_ID"] != "" && values["TTS_TOKEN"] != "" {
				values["TTS_PROVIDER"] = "doubao_native"
			}
		}
	}

	// ASR placeholders (if no real credentials)
	if values["ASR_API_KEY"] == "" && values["ASR_LOCAL_BIN"] == "" {
		setIfUnset("ASR_PROVIDER", "local")
		setIfUnset("ASR_LOCAL_BIN", "/usr/bin/true")
		setIfUnset("ASR_LOCAL_TEXT_PATH", "/dev/null")
		setIfUnset("ASR_READINESS_PROBE", "0")
	}

	// TTS selection
	if values["TTS_TOKEN"] == "" && values["TTS_LOCAL_BIN"] == "" {
		if env.SayTTS.Present {
			values["TTS_PROVIDER"] = "local_command"
			if bin, ok := env.SayTTS.Data["bin"].(string); ok {
				values["TTS_LOCAL_BIN"] = bin
			}
			values["TTS_LOCAL_ARGS"] = "-o {out} {text}"
			values["TTS_LOCAL_OUTPUT_FORMAT"] = "aiff"
		} else {
			setIfUnset("TTS_PROVIDER", "mock")
		}
	}

	return values
}
